# fly.toml app configuration file generated for kependudukan-karangbendo on 2024-08-06T20:26:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kependudukan-karangbendo'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  APP_URL='https://kependudukan-karangbendo.fly.dev'
  DB_CONNECTION='pgsql'
  DB_HOST='aws-0-ap-southeast-1.pooler.supabase.com'
  DB_PORT='5432'
  DB_DATABASE='postgres'
  DB_USERNAME='postgres.fcnceqdgetyqrttaorsq'
  DB_PASSWORD='Agungtok12..'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.port]]
    force_https = true
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443
